spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  # 所有Entity别名类所在包
  type-aliases-package: com.lirt.springcloud.entity
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: lirt-microservicecloud8001
  company.name: www.lirt.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
# 打印sql
logging:
  level:
    com:
      lirt:
        springcloud:
          mapper: debug
---
server:
  port: 8001


spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC       
    username: root
    password: 123456

mybatis:
  # 所有Entity别名类所在包
  type-aliases-package: com.lirt.springcloud.entity
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: lirt-microservicecloud8001
  company.name: www.lirt.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
# 打印sql
logging:
  level:
    com:
      lirt:
        springcloud:
          mapper: debug
